### ISSUE TITLE
Do not cancel the stream under any circumstances

### ISSUE THREAD

**Issue by mdedetrich** [knutwalker/akka-stream-json#16]
In diagnosing the issue here https://github.com/akka/akka-http/issues/1459, we found an apparent root cause.

It turns out that under some circumstances, akka-stream-json can cancel the JSON stream which ends up propagating and cancelling the HTTP connection stream (causing the `UnexpectedConnectionClosureException` issue)

Would it be possible to make sure the akka-stream-json will never cancel the stream that it is working on? There is also an issue on akka-http end here https://github.com/akka/akka-http/issues/1479 to add a feature so that cancelling the entity stream will not cancel the connection.

**Comment by knutwalker** [comment]
That's probably from https://github.com/knutwalker/akka-stream-json/blob/b5b85b3c1226936e6faad397660b4da90eb7046e/stream-json/src/main/scala/de/knutwalker/akka/stream/JsonStreamParser.scala#L88-L99 
I can change that for sure, never cancelling the stream sounds like a good thing, actually.

**Comment by mdedetrich** [comment]
@jrudolph This looks like the issue

@knutwalker Is it specifically https://github.com/knutwalker/akka-stream-json/blob/b5b85b3c1226936e6faad397660b4da90eb7046e/stream-json/src/main/scala/de/knutwalker/akka/stream/JsonStreamParser.scala#L96 which is likely to cancel the stream, or is it also https://github.com/knutwalker/akka-stream-json/blob/b5b85b3c1226936e6faad397660b4da90eb7046e/stream-json/src/main/scala/de/knutwalker/akka/stream/JsonStreamParser.scala#L90 ?

I guess there is also a decision we need to make about whether or not we should cancel the stream under any circumstances. If there is a JSON parsing exception that we should never cancel the stream, but under what other circumstances can akka-stream-json "fail"?

But yes, changing it is definitely a good idea. We have had issues in production because our http connections were getting cancelled, and it took a lot of diagnosing to figure out why

**Comment by knutwalker** [comment]
I just refactored the parser stage a bit, it doesn't use cancel anymore and uses the supervisor to decide whether to stop or not: https://github.com/knutwalker/akka-stream-json/blob/3ffa9b6d4eb596b34a54c75820ce0e09c470e07b/stream-json/src/main/scala/de/knutwalker/akka/stream/JsonStreamParser.scala#L65-L129.

**Comment by mdedetrich** [comment]
Cool, @jrudolph does this look correct to you?

**Comment by jrudolph** [comment]
Hi there,

let me start by stating that the original issue is a problem in Akka Http (https://github.com/akka/akka-http/issues/1459) and not one in here. There are certainly legitimate causes for cancelling a stream as it will prevent keeping a process running (like receiving an entity from a connection) when it isn't used any more. There's a bit of a trade-off that it might be more efficient just to ignore the remaining data versus actually cancelling. What to do obviously depends on what data you expect to remain on the stream and when it would arrive (which might be impossible to know). So, it's "wait for expected completion" versus "cancel right away".

In the case of this library the cancellation doesn't seem to be caused by explicit cancelling but by using `head` on an entity stream which will cancel after the first element read. I think that's done here:

https://github.com/knutwalker/akka-stream-json/blob/b5b85b3c1226936e6faad397660b4da90eb7046e/http-json/src/main/scala/de/knutwalker/akka/http/JsonSupport.scala#L38

Can you explain why `head` is being used? Is it because there might be another JSON document starting after the first one read? That seems like an uncommon case. It might make sense to change the `head` here to something else which just assert that there's only one thing and then waits for completion (and fails otherwise).

Regarding the change you did, I don't think it will change the behavior, because `completeStage` will also cancel all inputs (which is the right thing do).

**Comment by knutwalker** [comment]
I'm not too sure why exactly I chose to use `head` there. The `Unmarshaller` requires a `Future[J]`, `head` was probably the easy choice to get the type instead of properly consuming `dataBytes`. I just changed it to use reduce to use the first element that is emitted while also failing if there is no element and consuming the input source completely.

**Comment by mdedetrich** [comment]
@knutwalker Awesome thanks

@jrudolph Is it looking good now?

**Comment by mdedetrich** [comment]
@knutwalker Is it at a good stage to test right now? I can test in a separate branch with specific logging to ensure that stuff is working as expected

**Comment by knutwalker** [comment]
@mdedetrich Yes, I published the snapshot to bintray

```
resolvers += Resolver.bintrayRepo("knutwalker", "maven")
libraryDependencies += "de.knutwalker" %% "akka-http-circe" % "3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43"
```

**Comment by mdedetrich** [comment]
@knutwalker Brilliant thanks, I will report my findings here

**Comment by mdedetrich** [comment]
@knutwalker I am not able to find the jar

```
[error]         not found:
[error]             /Users/mdedetrich/.ivy2/local/de.knutwalker/akka-stream-circe_2.11/3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/de/knutwalker/akka-stream-circe_2.11/3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43/akka-stream-circe_2.11-3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43.pom
[error]             https://dl.bintray.com/knutwalker/maven/de/knutwalker/akka-stream-circe_2.11/3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43/akka-stream-circe_2.11-3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43.pom
[error]             https://maven.zalando.net/content/repositories/releases/de/knutwalker/akka-stream-circe_2.11/3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43/akka-stream-circe_2.11-3.5.0-a7b8e1b0642ebbf37d0b888079b06cc80b2f0d43.pom
```

**Comment by knutwalker** [comment]
@mdedetrich sorry about that, I did only publish for 2.12 as there was a warning that killed the 2.11 compile task. I have now added the 2.11 binaries as well.

**Comment by mdedetrich** [comment]
@knutwalker @jrudolph Okay so I have used the snapshot version of akka-http-json and I have received the following error

```
java.util.NoSuchElementException: No complete json entity consumed
at de.knutwalker.akka.http.JsonSupport$FirstElementSinkStage$$anon$1.onUpstreamFinish(JsonSupport.scala:64)
at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
```

I think that this may be a corner case where if akka-http cancels an upstream connection then akka-http-json doesn't know how to handle this? What do you guys think?

**Comment by knutwalker** [comment]
This exception would be thrown if you wanted to unmarshall some request entity, e.g. in a route, and the entity did complete its input before a single json object could be parsed.

**Comment by mdedetrich** [comment]
I checked the JSON for when it happened and it appeared to be completely valid JSON, it seems that there may be a corner case where akka-http is cancelling the entity stream. @jrudolph Any ideas?

**Comment by mdedetrich** [comment]
EDIT: 
> and the entity did complete its input before a single json object could be parsed.

By Json object, do you mean a literal json object (i.e. between `{` and `}`). If so, there are corner cases to be handled, no?

**Comment by mdedetrich** [comment]
@knutwalker Turns out this wasn't a problem with akka-stream-json and it was indeed that the stream was legitimately empty (we just wrote test cases to verify this).

As far as I can see, you can release the current develop branch as a new version of akka-stream-json

**Comment by mdedetrich** [comment]
Closing this as it appears to be resolved
